#!/bin/sh

set -x
set -e

exec > /var/log/setup-machine.log 2>&1

source /etc/heatconfig

# For some reason the volume id is shortened to 27 characters when the device
# link in /dev/disk/by-id/ is created. Account for this by truncating the
# device name accordingly.

volume_dev=$(printf '%.43s\n' $DB_VOLUME_DEV)

# Only format volume if it hasn't already been formatted.

if ! file -Ls $volume_dev | grep -q "filesystem data" ; then
    mkfs.ext4 "$volume_dev"
fi

mkdir -p /dbvolume
mount -t ext4 $volume_dev /dbvolume

### Mock code below this point. Fill in actual code for your application. ###

echo "$(date): Another record in the mock database for the $APP_NAME application." >> /dbvolume/mydb
cat > /etc/mock-dbusers <<EOF
root:verysecret
${DB_USER}:${DB_PASS}
EOF

cat > /etc/motd <<EOF
This node has been set up as the mock database server for ${APP_NAME}.

You will find 

* A mounted volume with a mock database in /dbvolume
* A mockup database user configuration in /etc/mock-dbusers
* This message in /etc/motd

EOF
