#!/bin/sh

set -x
set -e

exec > /var/log/setup-machine.log 2>&1

source /etc/heatconfig


# For some reason the volume id is shortened to 27 characters when the device
# link in /dev/disk/by-id/ is created. Account for this by truncating the
# device name accordingly.

volume_dev=$(printf '%.43s\n' $APP_VOLUME_DEV)

# Only format volume if it hasn't already been formatted.

if ! file -Ls $volume_dev | grep -q "filesystem data" ; then
    mkfs.ext4 "$volume_dev"
fi

mkdir -p /appvolume
mount -t ext4 $volume_dev /appvolume

cat > /opt/start-oscm.sh <<EOF
#/bin/sh

# check if docker is running
if ! docker ps &>/dev/null; then
  echo "starting docker service"
  systemctl start docker.service
fi

# ensure that postgres starts before glassfish
if ! docker inspect servicecatalog/oscm-db &>/dev/null; then
    docker pull servicecatalog/oscm-db >/dev/null
fi

docker rm -f oscm-postgres &>/dev/null
docker run -i --name oscm-db servicecatalog/oscm-db &
sleep 5
docker rm -f oscm-app &>/dev/null
docker run -i -p 8080:8080 --link oscm-db:postgres --name oscm-app servicecatalog/oscm-app
EOF

chmod +x /opt/start-oscm.sh

cat > /opt/stop-oscm.sh <<EOF
#/bin/sh

echo "oscm is being stopped"
docker rm -f oscm-db &>/dev/null &&
docker rm -f oscm-app &>/dev/null
EOF

chmod +x /opt/stop-oscm.sh

cat > /etc/systemd/system/oscm.service <<EOF
[Unit]
Description=OSCM conainerized
Requires=docker.service
After=docker.service

[Service]
ExecStart=/usr/bin/sh /opt/start-oscm.sh
ExecStop=/usr/bin/sh /opt/stop-oscm.sh

[Install]
WantedBy=default.target
EOF

systemctl enable docker.service
systemctl enable oscm.service
systemctl start oscm.service


mkdir -p /appvolume/${APP_NAME}/data

if [ ! -x /appvolume/mock-appconfig ]; then
    cat > /appvolume/mock-appconfig <<EOF
[DEFAULT]
data_dir = /appvolume/${APP_NAME}/data

[database]
user = ${DB_USER}
password = ${DB_PASS}
host = ${DB_HOST}
EOF
fi

echo "# updated at $(date)" >> /appvolume/mock-appconfig

cat > /etc/motd <<EOF
This node has been set up as the mock database server for ${APP_NAME}.

You will find

* A mockup application config file in /appvolume/mock-appconfig with a
  timestamp appended to include redeployment every time the application.yaml
  template is re-instantiated.
* A persistent application data volume mounted at /appvolume
* A mockup data directory in /appvolume/${APP_NAME}/data
* This message in /etc/motd

EOF

docker run --rm -i --net=host --name oscm-postgres servicecatalog/postgres
docker run --rm -i --net=host --name oscm-glassfish servicecatalog/glassfish
