#!/bin/sh

# Writes the configuration parameters passed in by Heat/cloud-init to /etc/heatconfig.

touch /etc/heatconfig
chmod 400 /etc/heatconfig

cat > /etc/heatconfig <<EOF
export APP_VOLUME_DEV=$APP_VOLUME_DEV
export DB_VOLUME_DEV=$DB_VOLUME_DEV
export DB_HOST=$DB_HOST
export DB_USER=$DB_USER
export DB_PASS=$DB_PASS
export APP_NAME=$APP_NAME
EOF
